# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter beryllium dipper equuleus perseus polaris ursa,$(TARGET_DEVICE)),)

endif
